### ISSUE TITLE
vagrant provision fails if cloned with a different folder name

### ISSUE THREAD

**Issue by mikeselander** [Chassis/vip-classic#11]
If you clone out the vip-classic extension with any other folder name than `vip-classic` then `vagrant provision` will fail on this line: https://github.com/Chassis/vip-classic/blob/master/modules/vip/manifests/init.pp#L4

It might be a bit of an edge case, but that static folder name feels a bit like a magic number and makes the setup more fragile then it should be imho.

**Comment by stuartshields** [comment]
@mikeselander Other Extensions within Chassis work the same way. I'm not sure if this is really an issue? It's part of the install steps to use that particular extension name.

**Comment by stuartshields** [comment]
@mikeselander Don't mind me. I'll fix this tonight.

**Comment by mikeselander** [comment]
Thanks Stuart :)

To be fair, you're totally right that it's not an issue strictly - it would just be nice to have a more flexible structure in case someone chooses a different name to clone down...

**Comment by rmccue** [comment]
FWIW, this behaviour will be enshrined into Chassis with v2 of the extensions API, since the class name will have to match the extension name.

**Comment by stuartshields** [comment]
@mikeselander See @rmccue comments above.

**Comment by mikeselander** [comment]
@stuartshields yes, I saw the above.

**Comment by BronsonQuick** [comment]
I'm closing this issue as I'm adding in https://github.com/Chassis/vip-classic/issues/16 so we won't be able to fix this.
