### ISSUE TITLE
Updating VIP Plugins

### ISSUE THREAD

**Issue by lgedeon** [Chassis/vip-classic#15]
Hi Guys,

I have been running vip-classic for a few months with no problems. Thank you!

It is now time to update my VIP Plugins. What is the best way to do that to stay compatible with vip-classic?

**Comment by BronsonQuick** [comment]
Hey @lgedeon! I haven't used this extension in a while but I think the best way to do it would be to run `git pull` in both the `plugins` and `mu-plugins` folders. @stuartshields should be able to confirm this for you.

**Comment by stuartshields** [comment]
@BronsonQuick That's correct. @lgedeon if you have any issues let me know.

**Comment by lgedeon** [comment]
I ran `git pull` in the plugins folder and it claims I am up to date, but I have reason to believe that there is a newer version of facebook-instant-articles. Also there isn't a .git folder inside either of those folders so running `git pull` just updates vip-classic, right?

**Comment by stuartshields** [comment]
@lgedeon When you say you ran it inside of the plugins folder. Are you talking about `themes/vip/plugins/`? This is where all of the VIP plugins live.

**Comment by lgedeon** [comment]
I ran it in both `content/themes/vip/plugins/` and `content/plugins/` for good measure. I also ran `git status` in both folders and that pointed back to the chassis root.

**Comment by stuartshields** [comment]
This plugin doesn't add anything to `content/plugins/`. So no need to worry about doing that in the future.

It looks like it's syncing from `https://vip-svn.wordpress.com/plugins/`. Can you please compare https://github.com/svn2github/wordpress-vip-plugins to what you have locally? 

Also I don't see any new version of Facebook Instant Articles in `https://vip-svn.wordpress.com/plugins/`. You may need to confirm with VIP if they've actually approved the new plugin yet.

**Comment by lgedeon** [comment]
hmm... I must be doing this wrong, but I was thinking if they are at 4.0.3 here https://github.com/Automattic/facebook-instant-articles-wp/milestone/18?closed=1 that they would at least have something close to that in the VIP plugins.

**Comment by stuartshields** [comment]
@lgedeon They need to approve the plugin to be used on VIP. I'd suggest opening up a zendesk ticket with them and ask them when they'll be releasing it VIP sites. Closing this off, as I don't think this is related to the extension anymore.

**Comment by lgedeon** [comment]
Yeah, looks that way. Sorry. But at least I know how to update vip-plugins, when the time comes. Thanks!
